name: Mr Dave Charlton
favicon: null
layout_spectrum: 0
typography_spectrum: 0.96523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#f8f8f8'
    - '#969696'
    - '#afafaf'
    - '#767676'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
