name: Mr Dave Charlton
favicon: null
layout_spectrum: 0.56898687267676
typography_spectrum: 0.10010001785121858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#f8f8f8'
    - '#969696'
    - '#afafaf'
    - '#767676'
  brandStrength: 1
  lightness: 0.3329677968285978
  saturation: 0.9507066220976412
  rhythmicContrast: 0.5567961654160172
purpose: []
